<?xml version="1.0"?>
<robot name="gopigo3" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants -->
  <xacro:property name="PI" value="3.1415926535897931"/>

  <!-- Robot dimensions -->
  <xacro:property name="base_width" value="0.110"/>
  <xacro:property name="base_length" value="0.140"/>
  <xacro:property name="base_height" value="0.070"/>

  <xacro:property name="wheel_radius" value="0.033"/>
  <xacro:property name="wheel_width" value="0.022"/>
  <xacro:property name="wheel_separation" value="0.117"/>

  <xacro:property name="caster_radius" value="0.015"/>
  <xacro:property name="caster_offset_x" value="0.050"/>

  <!-- Colors -->
  <material name="black">
    <color rgba="0.1 0.1 0.1 1"/>
  </material>

  <material name="red">
    <color rgba="0.8 0.1 0.1 1"/>
  </material>

  <material name="white">
    <color rgba="0.9 0.9 0.9 1"/>
  </material>

  <!-- Base footprint (virtual link on the ground) -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- Base link (robot body) -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="red"/>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    </visual>

    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    </collision>

    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001"/>
    </inertial>
  </link>

  <!-- Left wheel -->
  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
    </visual>

    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
    </collision>

    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001"/>
    </inertial>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="0 ${wheel_separation/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Right wheel -->
  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
    </visual>

    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
    </collision>

    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001"/>
    </inertial>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="0 ${-wheel_separation/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Front caster wheel -->
  <link name="front_caster">
    <visual>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="white"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>

    <collision>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>

    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.00001" ixy="0.0" ixz="0.0"
               iyy="0.00001" iyz="0.0"
               izz="0.00001"/>
    </inertial>
  </link>

  <joint name="front_caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_caster"/>
    <origin xyz="${caster_offset_x} 0 ${-wheel_radius + caster_radius}" rpy="0 0 0"/>
  </joint>

  <!-- Back caster wheel -->
  <link name="back_caster">
    <visual>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="white"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>

    <collision>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>

    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.00001" ixy="0.0" ixz="0.0"
               iyy="0.00001" iyz="0.0"
               izz="0.00001"/>
    </inertial>
  </link>

  <joint name="back_caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="back_caster"/>
    <origin xyz="${-caster_offset_x} 0 ${-wheel_radius + caster_radius}" rpy="0 0 0"/>
  </joint>

  <!-- LiDAR mount (will be used later for SLAM) -->
  <link name="laser_frame">
    <visual>
      <geometry>
        <cylinder radius="0.025" length="0.04"/>
      </geometry>
      <material name="black"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
  </link>

  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser_frame"/>
    <origin xyz="0 0 ${base_height + 0.02}" rpy="0 0 0"/>
  </joint>

</robot>
